<?php namespace ProcessWire;

/**
 * Page IDs Fieldtype for ProcessWire CMS/CMF
 *
 * Field that stores Page IDs as simple, numeric values. See README.md for more
 * details.
 * 
 * For documentation about the fields used in this class, please see:  
 * /wire/core/Fieldtype.php
 * 
 * @copyright 2018 Teppo Koivula
 * @license http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License, version 2
 */
class FieldtypePageIDs extends FieldtypeMulti {

    /**
     * Return information about this module
     * 
     * @return array
     */
    public static function getModuleInfo() {
        return [
            'title' => 'Page IDs',
            'summary' => 'Field that stores Page IDs',
            'author' => 'Teppo Koivula',
            'version' => '0.12.0',
            'requires' => 'ProcessWire>=3.0.98',
            'autoload' => true,
        ];
    }

    /**
     * Initialize this Fieldtype
     *
     */
    public function init() {
        parent::init();
        $dir = dirname(__FILE__);
        require_once(__DIR__ . "/PageID.php"); 
        $this->addHookAfter('FieldtypePage::getCompatibleFieldtypes', $this, 'hookFieldtypePageGetCompatibleFieldtypes');
    }

	/**
	 * Default inputfield
	 * 
	 * @var string
	 */
	protected $defaultInputfield = 'InputfieldAsmSelect';
    
    /**
     * Supported inputfields
     * 
     * @var array
     */
    protected $supportedInputfields = [
        'InputfieldAsmSelect',
        'InputfieldCheckboxes',
        'InputfieldPageAutocomplete',
        'InputfieldText',
    ];
    
    /**
     * Config inputfields for field settings
     * 
     * @param Field $field
	 * @return InputfieldWrapper
     */
    public function ___getConfigInputfields(Field $field) {
        
        $inputfields = parent::___getConfigInputfields($field);
        
        $f = $this->modules->get("InputfieldText");
        $f->name = "findPagesSelector";
        $f->label = $this->_("Selector string");
        $f->value = $field->{$f->name};
        $inputfields->append($f);
        
        $f = $this->modules->get("InputfieldSelect");
        $f->name = "inputfield";
        $f->label = $this->_("Input field type");
        foreach ($this->supportedInputfields as $inputfield) {
            $f->addOption($inputfield, $inputfield);
        }
        $f->value = $field->{$f->name} ?: $this->defaultInputfield;
        $inputfields->append($f);
        
        return $inputfields;
        
    }
    
    /**
     * Get a blank value for this fieldtype
     * 
     * @param Page $page
     * @param Field $field
     * @return array
     */
    public function getBlankValue(Page $page, Field $field) {
        return $this->wire(new WireArray());
    }

    /**
	 * Per the Fieldtype interface, sanitize the combined value for use in a Page
     * 
     * @param Page $page
     * @param Field $field
     * @param mixed $value
     * @return array
     */
    public function sanitizeValue(Page $page, Field $field, $value) {

        $out = $this->getBlankValue($page, $field);

        // string or integer values: sanitize and convert to an array
        if (is_string($value) || is_int($value)) {
            if (strpos($value, "|")) {
                $value = explode("|", $value);
            } else {
                $value = [$value];
            }
        }
        
        // Page object: enclose in an array
        if ($value instanceof Page) {
            $value = [$value];
        }
        
        if (is_array($value) || $value instanceof WireArray) {
            
            // Selector for validating items
            $selector = $this->getSelector($page, $field, 'sanitizeValue');
            
            foreach ($value as $key => $item) {
                // if item is an integer or a string with integer value ...
                if (is_int($item) || is_string($item) && (int) $item == $item) $item = $this->pages->get($item);
                // if item is an instance of PageID with an integer value ...
                if ($item instanceof PageID && is_int($item->value)) $item = $this->pages->get($item->value);
                // if at this point item is a Page object, we can validate it
                if ($item instanceof Page) {
                    if (!$selector || $item->is($selector)) {
                        $out->add($this->getSingleValue($field, $item->id));
                    }
                }
            }
            
        }
        
        return $out;
        
    }
    
    /**
     * Get single value object
     * 
     * @param Field $field
     * @param mixed $value
     */
    public function getSingleValue(Field $field, $value) {
        $out = new PageID;
        $out->value = $value !== null ? (int) $value : null;
        return $out;
    }
    
    /**
     * Process the value to convert it from an array to a WireArray containing
     * PageID objects
     * 
     * @param Page $page
     * @param Field $field
     * @param array $value
     * @return WireArray
     */
    public function ___wakeupValue(Page $page, Field $field, $value) {
        $out = $this->getBlankValue($page, $field);
        if (!empty($value)) {
            foreach ($value as $val) {
                $out->add($this->getSingleValue($field, $val));
            }
        }
        return $out;
    }
    
    /**
	 * Given an 'awake' value, as set by wakeupValue, convert the value back
     * to a basic array for database storage
     * 
     * @param Page $page
     * @param Field $field
     * @param WireArray $value
     * @return array
     */
    public function ___sleepValue(Page $page, Field $field, $value) {
        $out = [];
        foreach ($value as $item) {
            if ($item instanceof PageID) {
                $item = (int) $item->value;
            }
            if (is_int($item) && $item) {
                $out[] = $item;
            }
        }
        return $out;
    }

    /**
     * Format the value of the current field for output
     *
     * Note: this method is only used when output formatting is enabled.
     * 
     * @param Page $page
     * @param Field $field
     * @param array $value
     */
    public function ___formatValue(Page $page, Field $field, $value) {
        foreach ($value as $key => $item) {
            if (!is_int($item)) continue;
            $page = $this->pages->get($item);
            if ($page) {
                $value[$key] = $page;
            } else {
                unset($value[$key]);
            }
        }
        return $value;
    }
    
    /**
     * Return an Inputfield for editing the value of current field
     * 
     * @param Page $page
     * @param Field $field
     * @return Inputfield
     */
    public function getInputfield(Page $page, Field $field) {
        $inputfield_class = $field->get('inputfield');
        if (!$inputfield_class || !in_array($inputfield_class, $this->supportedInputfields)) {
            $inputfield_class = $this->defaultInputfield;
        }
        $inputfield = $this->modules->get($inputfield_class);
        if ($inputfield instanceof InputfieldPageAutocomplete) {
            $inputfield->set('value', explode("|", (string) $page->get($field->name)));
            // note: we can't seem to completely override the value, so it will
            // contain a WireArray as its last argument; remove it with a hook:
            $inputfield->addHookBefore('renderList', function(HookEvent $event) {
                $event->object->value = array_splice($event->object->value, 0, -1);
            });
        } else if (method_exists($inputfield, 'addOption')) {
            $selector = $this->getSelector($page, $field, 'getInputfield');
            if ($selector) {
                try {
                    $items = $this->wire('pages')->find($selector);
                    foreach ($items as $item) {
                        $inputfield->addOption($item->id, $item->title);
                    }
                } catch (WireException $e) {
                    $this->error($this->_("Erroneous selector string defined for field \"{$field->name}\" – please check the value for syntax errors!"));
                }
            }
        }
        return $inputfield; 
    }
    
    /**
     * Return selector string for finding and validating selectable items
     * 
     * @param Page $page
     * @param Field $field
     * @param string $context
     * @return string
     */
    public function ___getSelector(Page $page, Field $field, $context = null) {
        return $field->get('findPagesSelector');
    }
    
    /**
     * Get the database schema for this fieldtype
     * 
     * @param Field $field
     * @return array
     */
    public function getDatabaseSchema(Field $field) {
        $schema = parent::getDatabaseSchema($field);
        $schema['data'] = 'int NOT NULL';
        $schema['keys']['data'] = 'KEY data (data, pages_id, sort)';
        return $schema;
    }
    
    /**
     * Get Fieldtypes compatible with this one
     * 
	 * Returns a Fieldtypes object populated by fieldtypes that are compatible
     * with this one (i.e. ones the user may change the type to).
     * 
     * @param Field $field
     * @return Fieldtypes
     */
    public function ___getCompatibleFieldtypes(Field $field) {
        $fieldtypes = new Fieldtypes();
        $fieldtypes->add($this);
        $fieldtypes->add($this->wire('fieldtypes')->get('FieldtypePage'));
        return $fieldtypes;
    }

    /**
     * Make FieldtypePage consider FieldtypePageIDs as a compatible Fieldtype
     * 
     * @param HookEvent $event
     */
    public function hookFieldtypePageGetCompatibleFieldtypes(HookEvent $event) {
        $event->return->add($this);
    }

}
